"""
Generates Chapter_13.ipynb — Probability (Structural Engineering version)
Grounded in Hibbeler Chapter 1 (load return periods, design life) and structural reliability
"""
import json, os

def cell(ctype, cid, source, **kw):
    base = {"cell_type": ctype, "id": cid, "metadata": {}, "source": source}
    if ctype == "code":
        base.update({"execution_count": None, "outputs": []})
    base.update(kw)
    return base

CELLS = [
cell("markdown","title",[
"# Chapter 13: Probability in Structural Engineering\n",
"## What Are the Chances This Structure Survives Its Design Life?\n",
"\n",
"**Learning Objectives:**\n",
"- Define probability in terms of long-run frequency and apply it to structural load events\n",
"- Calculate the probability that an extreme load occurs at least once over a structure's design life\n",
"- Explain what a '100-year load' actually means — and what it does *not* mean\n",
"- Connect structural reliability to the everyday idea of probability\n",
]),

cell("markdown","photo",[
"<center>\n",
"<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/I-35W_Saint_Anthony_Falls_Bridge.jpg/1280px-I-35W_Saint_Anthony_Falls_Bridge.jpg' width='700' />\n",
"\n",
"<em>The St. Anthony Falls Bridge, Minneapolis — replacement for the I-35W bridge that collapsed in 2007. "
"Before opening in 2008, MnDOT placed 2 million pounds of test loads on the bridge and measured deflections "
"at dozens of locations. This is proof load testing in action. "
"(Wikimedia Commons — public domain.)</em>\n",
"</center>\n",
"\n",
"---\n",
]),

cell("code","setup",[
"import subprocess, sys\n",
"subprocess.run([sys.executable,'-m','pip','install','ipywidgets','--quiet'])\n",
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"import ipywidgets as widgets\n",
"from IPython.display import display\n",
"%matplotlib inline\n",
"np.random.seed(13)\n",
"print('Setup complete.')\n",
]),

cell("markdown","why",[
"## 13.1  Probability and Structural Design\n",
"\n",
"Every structure faces loads that cannot be known in advance — gusts of wind, earthquakes, heavy snowstorms, overloaded trucks. Structural engineers use **probability** to describe how likely these events are and to choose design loads that are appropriately conservative.\n",
"\n",
"The fundamental question is: **over the life of this structure, what is the probability it will be subjected to a load exceeding its design capacity?**\n",
"\n",
"Hibbeler §1.3 notes that design loads are specified by codes like ASCE 7-10 and are determined from *historical observation of loading events*. Those code values are not the absolute maximum load ever recorded — they are loads with a specified **annual probability of exceedance**. *(Note: Hibbeler references ASCE 7-10 for load values but does not derive return periods directly — that derivation lives in ASCE 7-10 itself. This chapter uses return periods as context for the probability concepts, not as textbook content students are expected to reproduce.)*\n",
"\n",
"### The Return Period\n",
"\n",
"A **return period** (also called a *recurrence interval*) of T years means:\n",
"\n",
"$$P(\\text{load exceeded in any one year}) = \\frac{1}{T}$$\n",
"\n",
"- A **50-year wind** has a 1/50 = **2% annual probability** of being exceeded\n",
"- A **100-year flood** has a 1/100 = **1% annual probability** of being exceeded\n",
"- A **475-year earthquake** has a 1/475 ≈ **0.21% annual probability** of being exceeded\n",
"\n",
"⚠️ **Common misconception:** A \"100-year flood\" does NOT mean it happens once every 100 years like clockwork. It means there is a 1% chance of it happening *in any given year* — which means it could happen two years in a row, or not at all for 200 years.\n",
]),

cell("markdown","exp1intro",[
"## 🔬 Interactive Experiment 1: Design Life vs. Return Period\n",
"\n",
"If there is a 1% chance of a load being exceeded in any single year, what is the probability it gets exceeded *at least once* over the structure's full design life?\n",
"\n",
"If each year is independent, the probability of the load being exceeded at least once in n years is:\n",
"\n",
"$$P(\\text{at least one exceedance in } n \\text{ years}) = 1 - \\left(1 - \\frac{1}{T}\\right)^n$$\n",
"\n",
"Use the sliders to explore how design life and return period interact.\n",
]),

cell("code","widget1",[
"def _lifetime_prob(return_period, design_life):\n",
"    p_annual = 1.0 / return_period\n",
"    p_lifetime = 1 - (1 - p_annual) ** design_life\n",
"\n",
"    years = np.arange(1, 151)\n",
"    curves = [\n",
"        (50,   'steelblue',  '50-yr return (wind)'),\n",
"        (100,  'darkorange', '100-yr return (flood)'),\n",
"        (475,  'firebrick',  '475-yr return (earthquake, 10% in 50yr)'),\n",
"        (2475, 'purple',     '2475-yr return (earthquake, 2% in 50yr)'),\n",
"    ]\n",
"\n",
"    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n",
"\n",
"    for T, color, label in curves:\n",
"        probs = 1 - (1 - 1/T)**years\n",
"        ax1.plot(years, probs*100, color=color, lw=2, label=label)\n",
"    ax1.axvline(design_life, color='black', lw=1.5, ls='--', label=f'Your design life: {design_life} yr')\n",
"    ax1.set_xlabel('Design Life (years)', fontsize=12)\n",
"    ax1.set_ylabel('Probability of At Least One Exceedance (%)', fontsize=12)\n",
"    ax1.set_title('Lifetime Exceedance Probability by Return Period', fontsize=13)\n",
"    ax1.legend(fontsize=9)\n",
"    ax1.set_ylim(0, 100)\n",
"\n",
"    # Right: bar for selected values\n",
"    selected_probs = []\n",
"    labels2 = []\n",
"    for T, color, label in curves:\n",
"        selected_probs.append((1-(1-1/T)**design_life)*100)\n",
"        labels2.append(label.split('(')[0].strip())\n",
"    bars = ax2.bar(labels2, selected_probs, color=[c[1] for c in curves], edgecolor='white')\n",
"    ax2.axhline(10, color='gray', ls=':', lw=1.5, label='10% threshold')\n",
"    for bar, val in zip(bars, selected_probs):\n",
"        ax2.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1, f'{val:.1f}%',\n",
"            ha='center', fontsize=10)\n",
"    ax2.set_ylabel('Probability of Exceedance (%)', fontsize=12)\n",
"    ax2.set_title(f'Over a {design_life}-Year Design Life', fontsize=13)\n",
"    ax2.set_ylim(0, 110)\n",
"    ax2.legend(fontsize=10)\n",
"    plt.tight_layout()\n",
"    plt.show()\n",
"\n",
"    print(f'\\nYour selection: T = {return_period} years, n = {design_life} years')\n",
"    print(f'P(at least one exceedance) = 1 - (1 - 1/{return_period})^{design_life} = {p_lifetime*100:.1f}%')\n",
"\n",
"w_T = widgets.IntSlider(value=100, min=10, max=2500, step=25,\n",
"    description='Return period T (yr):', style={'description_width':'initial'},\n",
"    layout=widgets.Layout(width='430px'))\n",
"w_n = widgets.IntSlider(value=50, min=5, max=150, step=5,\n",
"    description='Design life n (yr):', style={'description_width':'initial'},\n",
"    layout=widgets.Layout(width='430px'))\n",
"out1 = widgets.interactive_output(_lifetime_prob, {'return_period': w_T, 'design_life': w_n})\n",
"display(widgets.VBox([w_T, w_n, out1]))\n",
]),

cell("markdown","casestudy",[
"---\n",
"## ⚠️  Real-World Case: How AASHTO Chooses a 75-Year Return Period for Bridge Live Loads\n",
"\n",
"The **AASHTO LRFD Bridge Design Specifications** — the primary code for highway bridges in the United States — specify that bridge live loads shall be based on a **75-year return period**. Why 75 years? Because that is the standard design life for a new highway bridge.\n",
"\n",
"Here is the probability reasoning behind that choice:\n",
"\n",
"The AASHTO HL-93 design truck represents the heaviest vehicle load with approximately a "
"**1-in-75 annual probability** of being equaled or exceeded on a given bridge. "
"Over a 75-year design life:\n",
"\n",
"$$P(\\\\text{design load exceeded at least once}) = 1 - \\\\left(1 - \\\\frac{1}{75}\\\\right)^{75} \\\\approx 63\\\\%$$\n",
"\n",
"In other words, the AASHTO live load is **not** a load that will never be exceeded. It is a load with a 63% chance of being exceeded at least once over the bridge's life. Engineers accept this because:\n",
"\n",
"1. **Load factors** in AASHTO LRFD (1.75 × live load for the strength limit state) add a margin above the nominal design load\n",
"2. **Resistance factors** (φ ≈ 0.9 for bending) ensure the beam's actual strength exceeds the factored demand\n",
"3. Together, these keep the true probability of structural failure far below 63%\n",
"\n",
"The 75-year return period is not a guess — it is the answer to a specific probability question: *what load level, combined with appropriate safety factors, keeps bridge failure probability acceptably low over a standard design life?*\n",
"\n",
"> *Return periods in structural codes are chosen by working backward from acceptable risk — not forward from historical records alone.*\n",
]),

cell("markdown","exp2intro",[
"## 🔬 Interactive Experiment 2: Simulating a Bridge's Load History\n",
"\n",
"The simulation below generates a random load history for a bridge over its design life. Each year, there is a probability p that an extreme load event (flood, major storm, earthquake) occurs. Some years it happens. Some it does not. The randomness is real.\n",
"\n",
"Run the simulation many times and observe: even with the same probability, no two lifetime histories look the same — but the long-run statistics are stable.\n",
]),

cell("code","widget2",[
"def _simulate_lifetime(annual_prob_pct, design_life, n_simulations):\n",
"    p = annual_prob_pct / 100\n",
"    exceedances_per_life = []\n",
"    for _ in range(n_simulations):\n",
"        events = np.random.random(design_life) < p\n",
"        exceedances_per_life.append(events.sum())\n",
"\n",
"    theoretical = 1 - (1-p)**design_life\n",
"    simulated   = np.mean(np.array(exceedances_per_life) >= 1)\n",
"\n",
"    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n",
"\n",
"    # One example lifetime timeline\n",
"    example = np.random.random(design_life) < p\n",
"    years_hit = np.where(example)[0] + 1\n",
"    ax1.bar(range(1, design_life+1), np.ones(design_life)*0.3, color='lightgray', width=1)\n",
"    if len(years_hit):\n",
"        ax1.bar(years_hit, np.ones(len(years_hit)), color='firebrick', width=1,\n",
"            label=f'Exceedance ({len(years_hit)} events)')\n",
"    ax1.set_xlabel('Year', fontsize=12)\n",
"    ax1.set_yticks([])\n",
"    ax1.set_title(f'One Simulated {design_life}-Year Lifetime', fontsize=13)\n",
"    ax1.legend(fontsize=10)\n",
"\n",
"    # Distribution of exceedance count across simulations\n",
"    max_count = max(exceedances_per_life) + 1\n",
"    ax2.hist(exceedances_per_life, bins=range(0, max_count+1), color='steelblue',\n",
"        edgecolor='white', align='left', density=True)\n",
"    ax2.set_xlabel('Number of Exceedances in Design Life', fontsize=12)\n",
"    ax2.set_ylabel('Fraction of Simulated Lifetimes', fontsize=12)\n",
"    ax2.set_title(f'{n_simulations} Simulated Lifetimes', fontsize=13)\n",
"    ax2.annotate(\n",
"        f'Theoretical P(≥1): {theoretical*100:.1f}%\\nSimulated P(≥1):    {simulated*100:.1f}%',\n",
"        xy=(0.55, 0.82), xycoords='axes fraction', fontsize=10,\n",
"        bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.9))\n",
"    plt.tight_layout()\n",
"    plt.show()\n",
"\n",
"w_p  = widgets.FloatSlider(value=1.0, min=0.1, max=10.0, step=0.1,\n",
"    description='Annual P (%):', style={'description_width':'initial'},\n",
"    layout=widgets.Layout(width='430px'))\n",
"w_n  = widgets.IntSlider(value=50, min=10, max=150, step=5,\n",
"    description='Design life (yr):', style={'description_width':'initial'},\n",
"    layout=widgets.Layout(width='430px'))\n",
"w_ns = widgets.IntSlider(value=500, min=100, max=2000, step=100,\n",
"    description='Simulations:', style={'description_width':'initial'},\n",
"    layout=widgets.Layout(width='430px'))\n",
"out2 = widgets.interactive_output(_simulate_lifetime,\n",
"    {'annual_prob_pct': w_p, 'design_life': w_n, 'n_simulations': w_ns})\n",
"display(widgets.VBox([w_p, w_n, w_ns, out2]))\n",
]),

cell("markdown","review",[
"---\n",
"## 📋  Chapter 13 Review\n",
"\n",
"| Term | Meaning |\n",
"|------|--------|\n",
"| **Probability** | Long-run relative frequency of an event |\n",
"| **Annual exceedance probability** | Chance a load is exceeded in any single year: p = 1/T |\n",
"| **Return period T** | Average number of years between exceedances; T = 1/p |\n",
"| **Design life** | Number of years a structure is expected to serve |\n",
"| **Lifetime exceedance probability** | P(at least one exceedance in n years) = 1 − (1−p)ⁿ |\n",
"\n",
"**The Big Idea:** Structural engineers do not design for the worst load that has ever been observed — they design for the worst load with a specified probability of being exceeded over a structure's lifetime. Understanding that probability requires the same rules you learn in statistics: probability of complement, independent events, and the multiplication rule. A '100-year event' is not a prediction. It is a probability statement — and over a 50-year bridge life, there is nearly a 40% chance of experiencing one.\n",
]),
]

def build_notebook():
    nb = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
            "language_info": {"name":"python","version":"3.8.0"},
            "colab": {"provenance":[]},
        },
        "cells": CELLS,
    }
    out = os.path.join(os.path.dirname(__file__), '..', 'Chapter_13.ipynb')
    with open(out, 'w') as f: json.dump(nb, f, indent=1)
    print(f"Written → {os.path.abspath(out)}")

if __name__ == '__main__': build_notebook()
